### ISSUE TITLE
Tooltip cant be seen when shared and embed

### ISSUE THREAD

**Issue by vthb1992** [BT-OpenSource/bt-grafana-status-dot#4]
When hovering on the dot, the displayed tooltip was cropped out from the iframe when embed onto another webpage. 
![capture_dot_dashboard](https://user-images.githubusercontent.com/7752724/33975631-a450e676-e0ca-11e7-8401-dd885310eb36.JPG)

**Comment by krzyzakk** [comment]
Hi @vthb1992,

Thanks for pointing this out, we will look at publishing a fix when we get some time.

**Comment by jonasbleyl** [comment]
Hi @vthb1992 

Since we're using the built-in tooltip there's isn't much we can do to control it.
What we can do, however, is have the tooltip appear underneath instead which would then allow you to increase the height of the iframe and allow it to be completely visible.

<img width="177" alt="screen shot 2017-12-18 at 13 40 52" src="https://user-images.githubusercontent.com/12758226/34108766-3e067250-e3f9-11e7-9ada-12dd24a9150a.png">

Would that work for you?

**Comment by vthb1992** [comment]
Yes. Thats perfect.

**Comment by vthb1992** [comment]
Hi again. 
How to go about preventing the tooltip from displaying?

**Comment by jonasbleyl** [comment]
Hi. 
We'll add that fix I mentioned earlier so that the tooltip can be made visible.

Preventing the tooltip from showing at all, however, is not something that we'll be doing. This involves adding extra config options with little benefit since the tooltips are only visible when hovering over the dots anyway.

**Comment by vthb1992** [comment]
Hi
Thanks for the fix. Its working well. 
Is there any way to hide the value of each dot in the tooltip?

**Comment by jonasbleyl** [comment]
Hi, 
You could try setting the Display Value in the Values tab to: ""
And then set the Unit in Options to: locale format

**Comment by jonasbleyl** [comment]
Closing as this fix has now been deployed.
